Sujar Rajkarnikar (2507002) L5CG11

Problem - 1: Array Creation:



1. Initialize an empty array with size 2X2.

In [9]:
import numpy as np
arr_empty = np.empty((2,2))
print(arr_empty)

[[3.66667080e-315 0.00000000e+000]
 [6.91821741e-310 6.91821720e-310]]


2. Initialize an all one array with size 4X2.

In [10]:
arr_ones = np.ones((4,2))
print(arr_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [11]:
arr_full = np.full((3,3), 11)
print(arr_full);

[[11 11 11]
 [11 11 11]
 [11 11 11]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [12]:
a = np.array([[3,4,5],[6,7,8]])
zeros_like = np.zeros_like(a)
print(zeros_like)

[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [13]:
ones_like = np.ones_like(a)
print(ones_like)

[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [14]:
new_list = [1,2,3,4]
new_np_array = np.array(new_list)
print(new_np_array)

[1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [15]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [18]:
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [19]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [22]:
rand_arr = np.random.random(30)
mean_val = rand_arr.mean()
print(rand_arr)
print(mean_val)

[0.23292362 0.40989426 0.84626479 0.58342225 0.12422103 0.18429599
 0.83726103 0.59082144 0.18791081 0.81308584 0.70739558 0.54682451
 0.44292319 0.61695662 0.44711822 0.69876116 0.11077524 0.15387836
 0.60229726 0.26092767 0.55868466 0.93852072 0.51909446 0.06354996
 0.09528432 0.1916569  0.15931282 0.70165754 0.11250142 0.11330708]
0.42838429134982453


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [26]:
r10 = np.random.random((10,10))
min_val = r10.min()
max_val = r10.max()
print(r10)
print("the minimum value is = ",min_val)
print("the maximum value is = ",max_val)

[[3.28009712e-01 5.34486099e-01 2.18492270e-01 7.36238804e-01
  9.24020335e-01 8.90314580e-01 8.06406066e-01 6.46976560e-01
  9.27526089e-01 2.11955679e-01]
 [3.60722323e-02 3.90019758e-01 8.97452379e-01 3.53808910e-01
  4.56811735e-01 7.29674316e-01 8.28762943e-01 1.08457133e-01
  2.39770625e-01 2.60913807e-01]
 [6.17919609e-01 4.97411028e-01 9.04746896e-02 6.60545727e-01
  9.85331762e-01 8.04488573e-01 9.33267616e-01 7.71437718e-01
  6.05944730e-01 2.39979195e-01]
 [4.14902080e-01 7.20801051e-01 5.61722580e-01 1.20549592e-01
  3.90542610e-01 9.57431407e-02 5.80904096e-01 3.31193186e-02
  3.13427325e-01 4.93698848e-01]
 [8.02688347e-02 9.87171510e-01 8.09459334e-01 5.45860762e-01
  1.08618825e-01 7.83697148e-01 3.32141439e-01 9.82779111e-01
  8.55031133e-01 4.15750580e-01]
 [4.64777079e-01 4.11681221e-01 8.92600915e-01 4.27173175e-02
  3.47938267e-01 9.22942315e-02 5.37944801e-01 2.51114438e-01
  8.73059912e-01 4.71466990e-01]
 [8.82338408e-04 1.37187622e-01 5.65138888e-01 1.90124888e

6. Create a zero array of size 10 and replace 5th element with 1.

In [28]:
zero_arr = np.zeros(10)
zero_arr[4] = 1
print(zero_arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [31]:
arr_rev = np.array([1,2,0,0,4,0])[::-1]
print(arr_rev)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [34]:
square = np.ones((5,5))
square[1:-1,1:-1] = 0
print(square)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [36]:
checker = np.zeros((8,8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(checker)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [38]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
add = x + y
print(add)


[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [39]:
sub = x - y
print(sub)

[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [40]:
mul_int = x * 3
print(mul_int)

[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [41]:
squared = x**2
print(squared)

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [43]:
d1 = np.dot(v,w)
d2 = np.dot(x,v)
d3 = np.dot(x,y)
print(d1)
print()
print(d2)
print()
print(d3)


219

[29 77]

[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [45]:
concat_xy = np.vstack((x,y))
concat_vw = np.column_stack((v,w))
print(concat_xy)
print()
print(concat_vw)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]

[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [47]:
try:
    result = np.concatenate((x,v))
except Exception as e:
    print("Error:", e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Ans : all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:

For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

1) Prove A.A−1 = I.

In [49]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


A_inv = np.linalg.inv(A)
I = A @ A_inv
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [51]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB ≠ BA:", not np.array_equal(AB, BA))


AB ≠ BA: True


3. Prove (AB)

T = BTAT
# .

In [53]:
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("(AB)ᵀ = BᵀAᵀ:", np.array_equal(AB_T, BT_AT))

(AB)ᵀ = BᵀAᵀ: True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

In [54]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print(f"x = {X[0]}, y = {X[1]}, z = {X[2]}")

x = 2.0, y = 1.0, z = -2.0


Experiment: How Fast is Numpy?

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [56]:
import time
import numpy as np


size = 1000000
list1 = list(range(size))
list2 = list(range(size, size*2))
start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print(f"Python lists: {end-start:.4f} seconds")
arr1 = np.arange(size)
arr2 = np.arange(size, size*2)

start = time.time()
result_np = arr1 + arr2
end = time.time()
print(f"NumPy arrays: {end-start:.4f} seconds")

Python lists: 0.1237 seconds
NumPy arrays: 0.0040 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [58]:
start = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print(f"Python lists: {end-start:.4f} seconds")

start = time.time()
result_np = arr1 * arr2
end = time.time()
print(f"NumPy arrays: {end-start:.4f} seconds")

Python lists: 0.1257 seconds
NumPy arrays: 0.0024 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [59]:
start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print(f"Python lists: {end-start:.4f} seconds")

start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print(f"NumPy arrays: {end-start:.4f} seconds")


Python lists: 0.1086 seconds
NumPy arrays: 0.0019 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [60]:
size_mat = 1000
matrix1 = [[1]*size_mat for _ in range(size_mat)]
matrix2 = [[1]*size_mat for _ in range(size_mat)]

start = time.time()

result = [[0]*size_mat for _ in range(size_mat)]
end = time.time()
print(f"Python lists: >{end-start:.4f} seconds (too slow to implement fully)")

np_matrix1 = np.ones((size_mat, size_mat))
np_matrix2 = np.ones((size_mat, size_mat))

start = time.time()
result_np = np.dot(np_matrix1, np_matrix2)
end = time.time()
print(f"NumPy arrays: {end-start:.4f} seconds")

Python lists: >0.0210 seconds (too slow to implement fully)
NumPy arrays: 0.1232 seconds
